export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Landing/Hero";
export { default as Certified } from "./Landing/Certified";
export { default as CustomerStories } from "./Landing/CustomerStories";
export { default as Deliver } from "./Landing/Deliver";
export { default as NextSteps } from "./Landing/NextSteps";
export { default as Practice } from "./Landing/Practice";
export { default as UseCases } from "./Landing/UseCases";
export { default as Footer } from "./Footer";
